package ua.divas.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.ViewRowImpl;

import ua.divas.model.KontragentsImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 15 13:33:28 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CallCenterVORowImpl extends ViewRowImpl {


    public static final int ENTITY_KONTRAGENTS = 0;

    @Override
    public boolean isAttributeUpdateable(int i) {
        BigDecimal editable = this.getEditable();
        if (editable.intValue()==0) {
            return false;
        } else { 
        return super.isAttributeUpdateable(i);
            }
    }

    @Override
    protected void create(AttributeList attributeList) {
        this.setEditable(new BigDecimal(1));
        //this.setForValidation(new Integer(2));
        super.create(attributeList);
    }


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CityId,
        Deleted,
        Fullname,
        Id,
        Inn,
        IsBuyer,
        IsGroup,
        IsMeasurer,
        IsSupplier,
        Kpp,
        Namefull,
        Okpo,
        ParentId,
        Photo,
        Predefined,
        UrFiz,
        UserId,
        Version,
        Editable,
        LastOrder,
        LastOrderId,
        Phone,
        ContactId,
        Datzam,
        Comments,
        InfocardId,
        Created,
        ContactDetailsView,
        CityesView1,
        UsersView1,
        InfocardView1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CITYID = AttributesEnum.CityId.index();
    public static final int DELETED = AttributesEnum.Deleted.index();
    public static final int FULLNAME = AttributesEnum.Fullname.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int INN = AttributesEnum.Inn.index();
    public static final int ISBUYER = AttributesEnum.IsBuyer.index();
    public static final int ISGROUP = AttributesEnum.IsGroup.index();
    public static final int ISMEASURER = AttributesEnum.IsMeasurer.index();
    public static final int ISSUPPLIER = AttributesEnum.IsSupplier.index();
    public static final int KPP = AttributesEnum.Kpp.index();
    public static final int NAMEFULL = AttributesEnum.Namefull.index();
    public static final int OKPO = AttributesEnum.Okpo.index();
    public static final int PARENTID = AttributesEnum.ParentId.index();
    public static final int PHOTO = AttributesEnum.Photo.index();
    public static final int PREDEFINED = AttributesEnum.Predefined.index();
    public static final int URFIZ = AttributesEnum.UrFiz.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int EDITABLE = AttributesEnum.Editable.index();
    public static final int LASTORDER = AttributesEnum.LastOrder.index();
    public static final int LASTORDERID = AttributesEnum.LastOrderId.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int CONTACTID = AttributesEnum.ContactId.index();
    public static final int DATZAM = AttributesEnum.Datzam.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int INFOCARDID = AttributesEnum.InfocardId.index();
    public static final int CREATED = AttributesEnum.Created.index();
    public static final int CONTACTDETAILSVIEW = AttributesEnum.ContactDetailsView.index();
    public static final int CITYESVIEW1 = AttributesEnum.CityesView1.index();
    public static final int USERSVIEW1 = AttributesEnum.UsersView1.index();
    public static final int INFOCARDVIEW1 = AttributesEnum.InfocardView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CallCenterVORowImpl() {
    }

    /**
     * Gets Kontragents entity object.
     * @return the Kontragents
     */
    public KontragentsImpl getKontragents() {
        return (KontragentsImpl) getEntity(ENTITY_KONTRAGENTS);
    }

    /**
     * Gets the attribute value for CITY_ID using the alias name CityId.
     * @return the CITY_ID
     */
    public String getCityId() {
        return (String) getAttributeInternal(CITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_ID using the alias name CityId.
     * @param value value to set the CITY_ID
     */
    public void setCityId(String value) {
        setAttributeInternal(CITYID, value);
    }

    /**
     * Gets the attribute value for DELETED using the alias name Deleted.
     * @return the DELETED
     */
    public Integer getDeleted() {
        return (Integer) getAttributeInternal(DELETED);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETED using the alias name Deleted.
     * @param value value to set the DELETED
     */
    public void setDeleted(Integer value) {
        setAttributeInternal(DELETED, value);
    }

    /**
     * Gets the attribute value for FULLNAME using the alias name Fullname.
     * @return the FULLNAME
     */
    public String getFullname() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FULLNAME using the alias name Fullname.
     * @param value value to set the FULLNAME
     */
    public void setFullname(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for INN using the alias name Inn.
     * @return the INN
     */
    public String getInn() {
        return (String) getAttributeInternal(INN);
    }

    /**
     * Sets <code>value</code> as attribute value for INN using the alias name Inn.
     * @param value value to set the INN
     */
    public void setInn(String value) {
        setAttributeInternal(INN, value);
    }

    /**
     * Gets the attribute value for IS_BUYER using the alias name IsBuyer.
     * @return the IS_BUYER
     */
    public Integer getIsBuyer() {
        return (Integer) getAttributeInternal(ISBUYER);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_BUYER using the alias name IsBuyer.
     * @param value value to set the IS_BUYER
     */
    public void setIsBuyer(Integer value) {
        setAttributeInternal(ISBUYER, value);
    }

    /**
     * Gets the attribute value for IS_GROUP using the alias name IsGroup.
     * @return the IS_GROUP
     */
    public Integer getIsGroup() {
        return (Integer) getAttributeInternal(ISGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_GROUP using the alias name IsGroup.
     * @param value value to set the IS_GROUP
     */
    public void setIsGroup(Integer value) {
        setAttributeInternal(ISGROUP, value);
    }

    /**
     * Gets the attribute value for IS_MEASURER using the alias name IsMeasurer.
     * @return the IS_MEASURER
     */
    public Integer getIsMeasurer() {
        return (Integer) getAttributeInternal(ISMEASURER);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MEASURER using the alias name IsMeasurer.
     * @param value value to set the IS_MEASURER
     */
    public void setIsMeasurer(Integer value) {
        setAttributeInternal(ISMEASURER, value);
    }

    /**
     * Gets the attribute value for IS_SUPPLIER using the alias name IsSupplier.
     * @return the IS_SUPPLIER
     */
    public Integer getIsSupplier() {
        return (Integer) getAttributeInternal(ISSUPPLIER);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPPLIER using the alias name IsSupplier.
     * @param value value to set the IS_SUPPLIER
     */
    public void setIsSupplier(Integer value) {
        setAttributeInternal(ISSUPPLIER, value);
    }

    /**
     * Gets the attribute value for KPP using the alias name Kpp.
     * @return the KPP
     */
    public String getKpp() {
        return (String) getAttributeInternal(KPP);
    }

    /**
     * Sets <code>value</code> as attribute value for KPP using the alias name Kpp.
     * @param value value to set the KPP
     */
    public void setKpp(String value) {
        setAttributeInternal(KPP, value);
    }

    /**
     * Gets the attribute value for NAMEFULL using the alias name Namefull.
     * @return the NAMEFULL
     */
    public String getNamefull() {
        return (String) getAttributeInternal(NAMEFULL);
    }

    /**
     * Sets <code>value</code> as attribute value for NAMEFULL using the alias name Namefull.
     * @param value value to set the NAMEFULL
     */
    public void setNamefull(String value) {
        setAttributeInternal(NAMEFULL, value);
    }

    /**
     * Gets the attribute value for OKPO using the alias name Okpo.
     * @return the OKPO
     */
    public String getOkpo() {
        return (String) getAttributeInternal(OKPO);
    }

    /**
     * Sets <code>value</code> as attribute value for OKPO using the alias name Okpo.
     * @param value value to set the OKPO
     */
    public void setOkpo(String value) {
        setAttributeInternal(OKPO, value);
    }

    /**
     * Gets the attribute value for PARENT_ID using the alias name ParentId.
     * @return the PARENT_ID
     */
    public String getParentId() {
        return (String) getAttributeInternal(PARENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_ID using the alias name ParentId.
     * @param value value to set the PARENT_ID
     */
    public void setParentId(String value) {
        setAttributeInternal(PARENTID, value);
    }

    /**
     * Gets the attribute value for PHOTO using the alias name Photo.
     * @return the PHOTO
     */
    public BlobDomain getPhoto() {
        return (BlobDomain) getAttributeInternal(PHOTO);
    }

    /**
     * Sets <code>value</code> as attribute value for PHOTO using the alias name Photo.
     * @param value value to set the PHOTO
     */
    public void setPhoto(BlobDomain value) {
        setAttributeInternal(PHOTO, value);
    }

    /**
     * Gets the attribute value for PREDEFINED using the alias name Predefined.
     * @return the PREDEFINED
     */
    public Integer getPredefined() {
        return (Integer) getAttributeInternal(PREDEFINED);
    }

    /**
     * Sets <code>value</code> as attribute value for PREDEFINED using the alias name Predefined.
     * @param value value to set the PREDEFINED
     */
    public void setPredefined(Integer value) {
        setAttributeInternal(PREDEFINED, value);
    }

    /**
     * Gets the attribute value for UR_FIZ using the alias name UrFiz.
     * @return the UR_FIZ
     */
    public Integer getUrFiz() {
        return (Integer) getAttributeInternal(URFIZ);
    }

    /**
     * Sets <code>value</code> as attribute value for UR_FIZ using the alias name UrFiz.
     * @param value value to set the UR_FIZ
     */
    public void setUrFiz(Integer value) {
        setAttributeInternal(URFIZ, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Timestamp getVersion() {
        return (Timestamp) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Timestamp value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Editable.
     * @return the Editable
     */
    public BigDecimal getEditable() {
        return (BigDecimal) getAttributeInternal(EDITABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Editable.
     * @param value value to set the  Editable
     */
    public void setEditable(BigDecimal value) {
        setAttributeInternal(EDITABLE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute LastOrder.
     * @return the LastOrder
     */
    public String getLastOrder() {
        return (String) getAttributeInternal(LASTORDER);
    }

    /**
     * Gets the attribute value for the calculated attribute LastOrderId.
     * @return the LastOrderId
     */
    public String getLastOrderId() {
        return (String) getAttributeInternal(LASTORDERID);
    }

    /**
     * Gets the attribute value for the calculated attribute Phone.
     * @return the Phone
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Gets the attribute value for the calculated attribute ContactId.
     * @return the ContactId
     */
    public String getContactId() {
        return (String) getAttributeInternal(CONTACTID);
    }

    /**
     * Gets the attribute value for DATZAM using the alias name Datzam.
     * @return the DATZAM
     */
    public Timestamp getDatzam() {
        return (Timestamp) getAttributeInternal(DATZAM);
    }

    /**
     * Sets <code>value</code> as attribute value for DATZAM using the alias name Datzam.
     * @param value value to set the DATZAM
     */
    public void setDatzam(Timestamp value) {
        setAttributeInternal(DATZAM, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for INFOCARD_ID using the alias name InfocardId.
     * @return the INFOCARD_ID
     */
    public String getInfocardId() {
        return (String) getAttributeInternal(INFOCARDID);
    }

    /**
     * Sets <code>value</code> as attribute value for INFOCARD_ID using the alias name InfocardId.
     * @param value value to set the INFOCARD_ID
     */
    public void setInfocardId(String value) {
        setAttributeInternal(INFOCARDID, value);
    }

    /**
     * Gets the attribute value for CREATED using the alias name Created.
     * @return the CREATED
     */
    public Timestamp getCreated() {
        return (Timestamp) getAttributeInternal(CREATED);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED using the alias name Created.
     * @param value value to set the CREATED
     */
    public void setCreated(Timestamp value) {
        setAttributeInternal(CREATED, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContactDetailsView.
     */
    public RowIterator getContactDetailsView() {
        return (RowIterator) getAttributeInternal(CONTACTDETAILSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CityesView1.
     */
    public RowSet getCityesView1() {
        return (RowSet) getAttributeInternal(CITYESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UsersView1.
     */
    public RowSet getUsersView1() {
        return (RowSet) getAttributeInternal(USERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InfocardView1.
     */
    public RowSet getInfocardView1() {
        return (RowSet) getAttributeInternal(INFOCARDVIEW1);
    }

}

