package ua.divas.view;

import oracle.jbo.server.ViewObjectImpl;

import ua.divas.classes.DivasView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 16 10:59:47 EET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GuiSettingsViewImpl extends DivasView {
    /**
     * This is the default constructor (do not remove).
     */
    public GuiSettingsViewImpl() {
    }

    /**
     * Returns the bind variable value for u_id.
     * @return bind variable value for u_id
     */
    public String getu_id() {
        return (String) getNamedWhereClauseParam("u_id");
    }

    /**
     * Sets <code>value</code> for bind variable u_id.
     * @param value value to bind as u_id
     */
    public void setu_id(String value) {
        setNamedWhereClauseParam("u_id", value);
    }
}

